In [1]:
import numpy as np

### Array Operations

In [2]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(a)
print(type(a))
print(a.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
<class 'numpy.ndarray'>
(2, 5)


In [8]:
a= np.zeros((3,3))
print(a)

b =np.ones(3)
print(b)

c =np.full((3,4),5)
print(c)

rand = np.random.random(((2,3)))
print(rand)
##random number generated are between 0,1

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[0.71101692 0.03075446 0.12292182]
 [0.8450678  0.61510882 0.7599053 ]]


In [14]:
##matrix 
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

##element wise operation
print(x+y)
print(np.add(x,y))

print(x-y)
print(np.subtract(x,y))

print(x*y)
print(np.multiply(x,y))

print(x/y)
print(np.divide(x,y))

print(np.sqrt(x))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [17]:
##Matrix multiplication
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))



[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [18]:
##Vector Multiplication

a=np.array([1,2,3,4])
b=np.array([1,2,3,4])

print(a.dot(b))

30


In [22]:
print(x)
print(sum(x))
print(np.sum(x))
print(np.sum(x,axis=0))##along columns
print(np.sum(x,axis=1))##along rows

[[1 2]
 [3 4]]
[4 6]
10
[4 6]
[3 7]


In [25]:
##stack

print(a)
b=b**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [31]:
print(np.stack((a,b),axis=1))
print(np.stack((a,b),axis=0))

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]]
[[ 1  2  3  4]
 [ 1  4  9 16]]


In [42]:
x=np.stack((a,b),axis=0)
print(x)
x=x.reshape(4,2)
print(x)
x=x.reshape(8,)##converts it back to linear array
print(x)
x=x.reshape((2,-1))##automatically figures out numbers of columns needed for 2 rows
print(x)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
[ 1  2  3  4  1  4  9 16]
[[ 1  2  3  4]
 [ 1  4  9 16]]


# NUMPY Random Module

In [54]:
a=np.arange(10)##get all numbers between 0,10
print(a)
a=np.arange(10)+5 ##get all numbers between 5,15
print(a)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [57]:
np.random.shuffle(a)
print(a)

[11 14  8  6 13  7  5 12  9 10]


In [62]:
a = np.random.rand(2,3)
print(a)

[[0.58814199 0.19915279 0.32223563]
 [0.08808254 0.81774531 0.77916776]]
[[0.58814199 0.19915279 0.32223563]
 [0.08808254 0.81774531 0.77916776]]


In [70]:
a = np.random.randint(5,10,2)##we get 2 numbers in range 5-10
print(a)

element = np.random.choice([1,2,3,4,5,6])##choose a random number form yjr given array
print(element)

[6 6]
5


In [71]:
np.random.seed(1) 
##this ensures that everytime the code is run we get the same random number

# Statistical methods in Numnpy

In [76]:
a = np.array([[1,2,3,4],[7,8,9,0]])
print(a)
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

[[1 2 3 4]
 [7 8 9 0]]
0
[1 2 3 0]
[1 0]


In [77]:
##mean
b = np.array([1,2,3,4])
print(np.mean(b))

2.5


In [79]:
##standard Deviation
np.std(b)

1.118033988749895

In [80]:
##variance
np.var(b)

1.25