## Pandas

Dataframe to store data in a tabular form

In [1]:
import numpy as np
import pandas as pd

In [7]:
user_data = {
    "marksA":np.random.randint(1,100,5),
    "marksB":np.random.randint(1,100,5),
    "marksC":np.random.randint(1,100,5),
}
user_data

{'marksA': array([82, 91, 71, 38, 14]),
 'marksB': array([98, 22, 12, 63, 35]),
 'marksC': array([75, 42, 66, 28, 87])}

In [15]:
df=pd.DataFrame(user_data,dtype='float32')
print(df)

   marksA  marksB  marksC
0    82.0    98.0    75.0
1    91.0    22.0    42.0
2    71.0    12.0    66.0
3    38.0    63.0    28.0
4    14.0    35.0    87.0


In [11]:
df.head(n=3)

marksA  marksB  marksC
0      82      98      75
1      91      22      42
2      71      12      66

In [12]:
df.columns

Index(['marksA', 'marksB', 'marksC'], dtype='object')

In [16]:
df.to_csv('marks.csv')

In [19]:
mydata=pd.read_csv('marks.csv')
print(mydata)
mydata = mydata.drop(columns=['Unnamed: 0'])
print(mydata)

   Unnamed: 0  marksA  marksB  marksC
0           0    82.0    98.0    75.0
1           1    91.0    22.0    42.0
2           2    71.0    12.0    66.0
3           3    38.0    63.0    28.0
4           4    14.0    35.0    87.0
   marksA  marksB  marksC
0    82.0    98.0    75.0
1    91.0    22.0    42.0
2    71.0    12.0    66.0
3    38.0    63.0    28.0
4    14.0    35.0    87.0


In [21]:
mydata.describe()

marksA     marksB     marksC
count   5.000000   5.000000   5.000000
mean   59.200000  46.000000  59.600000
std    32.259882  34.806609  24.172298
min    14.000000  12.000000  28.000000
25%    38.000000  22.000000  42.000000
50%    71.000000  35.000000  66.000000
75%    82.000000  63.000000  75.000000
max    91.000000  98.000000  87.000000

In [22]:
mydata.tail()

marksA  marksB  marksC
0    82.0    98.0    75.0
1    91.0    22.0    42.0
2    71.0    12.0    66.0
3    38.0    63.0    28.0
4    14.0    35.0    87.0

In [24]:
df.iloc[3]##het a paricular row
df.iloc[3,1]##het a paricular row and column


63.0

In [26]:
## Sorting
mydata.sort_values(by=["marksA"],ascending=True)

marksA  marksB  marksC
4    14.0    35.0    87.0
3    38.0    63.0    28.0
2    71.0    12.0    66.0
0    82.0    98.0    75.0
1    91.0    22.0    42.0

In [29]:
data_array=mydata.values
print(type(data_array))
print(data_array)

<class 'numpy.ndarray'>
[[82. 98. 75.]
 [91. 22. 42.]
 [71. 12. 66.]
 [38. 63. 28.]
 [14. 35. 87.]]
